### PR TITLE
n64: enable parallel-RDP on Mac via MoltenVK

### PR DESCRIPTION
**Pull request by rasky**
This also updates the build system and the CI to produce universal binaries on Mac (amd64 + arm64).

### CODE REVIEW

**Comment by IIIIIIIllllllllIIIII** [comment]
how can I run it on m1 Mac? or is it still WIP?

**Comment by rasky** [comment]
> how can I run it on m1 Mac? or is it still WIP?

This has just been merged. You can either fetch a build from CI or compile it yourself.

**Comment by IIIIIIIllllllllIIIII** [comment]
mmmm its running fine but there is no way to choose upscaling or vulkan instead of open gl…. am i doing it wrong?

>>

**Comment by Screwtapello** [comment]
The N64 graphics options are in Settings → Video. If "Enable GPU acceleration" is ticked, you'll be using Vulkan (or Metal on macOS); if "HD Quality" or "UHD Quality" is selected, it'll be rendered at a higher internal resolution.

OpenGL should be selected in Settings → Drivers, since that controls how the emulated video is drawn to the screen, rather than how the video emulation is implemented.

**Pull request merged**
