### PR TITLE
removed auto-generated qt.moc

### PR DESCRIPTION
**Pull request by jeffythedragonslayer**
this file says that it was created by the Qt Meta Object Compiler and auto-generated files should generally be .gitignore'd

### CODE REVIEW

**Comment by LukeUsher** [comment]
Did you test building with “make hiro=qt4” or “hiro=qt5” to make sure this didn’t break the build when using qt as a driver? You may need to do this on a Linux machine though; im not sure we ever properly hooked up/tested Qt on windows.

**Comment by jeffythedragonslayer** [comment]
Not yet, I'm not sure how that is different from the checks github runs.

**Comment by Screwtapello** [comment]
For what it's worth, higan applied a very similar change very early on:

https://github.com/higan-emu/higan/commit/6673a1c0e9344dc22f87571519afd3fb6e7f27c3

It wasn't necessary to do anything else to keep Qt builds working; the only advantage of keeping the .moc committed is that you don't need the moc binary around to do a build. But if you have the Qt development libraries present to link against, it's extremely unlikely you wouldn't have the moc binary.

**Comment by jeffythedragonslayer** [comment]
I actually can't build ares at all, even on master branch:

```lto1: fatal error: bytecode stream in file ‘obj/libco.o’ generated with LTO version 11.2 instead of the expected 11.3```

uname -a reports:

```Linux bsnes-ubuntu 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by Screwtapello** [comment]
It works for me on Debian Testing, once I installed `lld`. You might want to `git clean` to get rid of files generated by older compilers first.

**Pull request merged**
