### PR TITLE
Fix halt bug

### PR DESCRIPTION
**Pull request by Meepster99**
This fixes the halt bug in gameboy emulators
A rom to test it can be found [here](https://github.com/retrio/gb-test-roms)

### CODE REVIEW

**Comment by Screwtapello** [comment]
If `haltBugTrigger()` is only called in one place, why is it in a separate function?

**Comment by Meepster99** [comment]
This is due to my lack of experience in large scale c++ projects, but I couldn't find a way to access the "status" variable from inside the SM83 namespace. 
Any way of cleaning it up would be appreciated.

**Comment by LukeUsher** [comment]
Could you please rebase this PR and then force-push? I ask because right now it duplicates the commits that were already merged from the previous PR

**Comment by Meepster99** [comment]
Hi! I think I rebased and force pushed the PR, but I am very new to github and am not sure.
Does this look good?

**Review by LukeUsher — APPROVED** [review]

**Pull request merged**
