### PR TITLE
encoder-calls: Windows support

### PR DESCRIPTION
**Pull request by MerryMage**
Add Win32 ABI support to amd64 recompiler.

Note that the Win32 ABI has a required allocation of 0x20 of shadow space for function calls.

### CODE REVIEW

**Comment by Screwtapello** [comment]
Coming from MerryMage, I assume this works, and I've seen Windows N64 screenshots on Discord, but just for the record I'd like somebody else on the maintenance team to say "I've tested this and it works" before I merge it.

**Comment by qeeg** [comment]
I've gotten Ridge Racer on PSX to boot and go ingame, if that means anything.

**Comment by Screwtapello** [comment]
I think only the N64 core uses the recompiler, not the PSX code.

**Comment by qeeg** [comment]
Ah, my bad, lemme recompile and check again then :p

**Comment by qeeg** [comment]
Good news! Super Mario 64 boots with this!

**Pull request merged**
