### PR TITLE
n64: Sets the initial values

### PR DESCRIPTION
**Pull request by jeltaqq**
I verified the initial values with test tools (COP0Cause, COP0Register, RDRAMTest).
https://github.com/PeterLemon/N64

### CODE REVIEW

**Comment by jeltaqq** [comment]
Here are the test results.
COP0Cause
COP0Cause
COP0Register
COP0Register
RDRAMTest
RDRAMTest

**Review by LukeUsher — CHANGES_REQUESTED** [review]
It would be better to set initial values in the power/reset functions, rather than in the class definition.

With this current approach, the initial values may not be restored when switching between games.

**Comment by rasky** [comment]
The RDRAM registers are not built-in values. They get configures like this by IPL3 RDRAM calibration which is currently broken because the RI is not fully emulated. I would not hardcore them as boot values because it's not how the hardware works.

**Comment by rasky** [comment]
The RDRAM registers are not built-in values. They get configured like this by IPL3 RDRAM calibration which is currently broken because the RI is not fully emulated. I would not hardcode them as boot values because it's not how the hardware works.

**Comment by LukeUsher** [comment]
@rasky also raises a good point, so at the very least, please include a comment to explain that it's a hack/workaround, so that we can revisit it later.

**Comment by jeltaqq** [comment]
Thanks for the good point. The RDRAM registers will be reverted as the less hacks the better. Also, COP0 sets the initial values in the power/reset function.

**Comment by bigbass1997** [comment]
> the less hacks the better.

Agreed. I'd rather keep the number of hacks/workarounds to a minimum.

**Comment by Shideravan** [comment]
I tested this commit with the latest code version, but didn't notice any emulation improvements on hard-setting these values. The compatibility with the latest ares dev build seems to be exactly the same as when these values aren't hardset for commercial games.
Probably because on booting N64 commercial games, the core quickly write over these values and the values hard-setted makes no difference.

**Comment by LukeUsher** [comment]
> The RDRAM registers are not built-in values. They get configured like this by IPL3 RDRAM calibration which is currently broken because the RI is not fully emulated. I would not hardcode them as boot values because it's not how the hardware works.

@rasky Would you be able to create an issue to document this, and then I can close this PR

**Comment by rasky** [comment]
@LukeUsher done: https://github.com/ares-emulator/ares/issues/350

**Pull request closed without merging**
