### PR TITLE
sh2: mirror cache control register

### LINKED ISSUE #1037: [32X] Virtua Fighter Bugs
There's a number of glaring bugs.

1. The hit detection is busted. Especially evident with moves that pounce someone on the ground, they will simply not register at all.
2. The AI seems pretty broken. It will even sometimes choose to not move or attack at all.
3. One of Wolf Hawkfield's grabs has a completely broken animation that causes you to float in the air behind him (You should be held above him).

I'm using ares v132. I tested this against PicoDrive.

file: Virtua Fighter (Japan, USA) (En).32x
sha256: C595E136C91A012B1E7D591ACFB9D965926CAC51ACEA998B90969D74391BFA08

### PR DESCRIPTION
**Pull request by invertego**
Fixes #1037

### CODE REVIEW

**Comment by LukeUsher** [comment]
I feel like it's worth mentioning that for most SH2 internal registers, MAME seems to map them to both addr and addr + 1

They didn't implement +1 for cache control, but their SH2 core does not actually emulate cache; so it doesn't matter there.

But this does lead credit to the theory that a lot of these registers have copies.

eg:

```
	map(0xfffffe80, 0xfffffe81).rw(FUNC(sh2_device::wtcnt_r), FUNC(sh2_device::wtcnt_w));
	map(0xfffffe82, 0xfffffe83).rw(FUNC(sh2_device::rstcsr_r), FUNC(sh2_device::rstcsr_w));
```

**Comment by invertego** [comment]
Those are not examples of MAME mirroring 8-bit registers. Those are examples of MAME implementing 16-bit registers.

Still, you are not wrong to suggest that there may be other mirrors.

**Comment by LukeUsher** [comment]
> Those are not examples of MAME mirroring 8-bit registers. Those are examples of MAME implementing 16-bit registers.
> 
> Still, you are not wrong to suggest that there may be other mirrors.

My bad; pro-tip: don’t look at code when sleep deprived :’)

**Comment by invertego** [comment]
Marking ready, though at some point I would still like to get some HW verification on this (I've written a test ROM for this express purpose) and if the results demonstrate the need for further changes I'll make a follow-up PR.

**Comment by LukeUsher** [comment]
We can reliably say that this mirror exists at this point in time, we just can't explain why/what other mirrors may exist, hardware testing will help that

**Pull request merged**
