### PR TITLE
Improving the readme section

### PR DESCRIPTION
**Pull request by Shideravan**
Including the project logo and a step-by-step compiling instructions for Windows x64

### CODE REVIEW

**Comment by LukeUsher** [comment]
a good idea overall, but in my opinion, the build instructions are better fitted to a GitHub wiki that we can link to, so that we can update as necessary without having to push new code to the repository. 

This would also allow build instructions to be more detailed, including the great deal of customisation options that can be passed to make.

There's also the issue of the community links; the ares team have not yet decided where the community will be focused going forward.

If you can cherry-pick 3aed376 and 99e0186 into a separate pull-request, I would be happy to merge those as-is

**Comment by Shideravan** [comment]
> a good idea overall, but in my opinion, the build instructions are better fitted to a GitHub wiki that we can link to, so that we can update as necessary without having to push new code to the repository.
> 
> This would also allow build instructions to be more detailed, including the great deal of customisation options that can be passed to make.
> 
> There's also the issue of the community links; the ares team have not yet decided where the community will be focused going forward.
> 
> If you can cherry-pick [3aed376](https://github.com/higan-emu/ares/commit/3aed3764f318f55176f749b9245b13ca5f2c6a88) and [99e0186](https://github.com/higan-emu/ares/commit/99e0186ea9f123482192ea5248f6353b2dcb79a2) into a separate pull-request, I would be happy to merge those as-is

Agreed. If you can create the wiki I can move these instructions there and post just a link here. Also, will be easier to put these instructions for more OS later.

8c0c9a5 is also really necessary, as the Sega CD image link is broken.

I'll remove then the community and building sections for now for the merge can be done.

**Comment by Shideravan** [comment]
What do you think to we include this badge as ares emulator developers is so proud of it's license?
[License: ISP](https://github.com/higan-emu/ares/blob/master/LICENSE)

**Comment by Shideravan** [comment]
I'll now add the new website too

**Comment by Shideravan** [comment]
Now it's updated with v123 status

**Comment by Shideravan** [comment]
I'm closing this because most of the information is better suited in our new website (https://ares-emulator.github.io/). 
I already cherrypicked the changes from this commit that do make sense in the README and now it's in the https://github.com/higan-emu/ares/pull/100

**Pull request closed without merging**
